# Generated by Django 2.1.1 on 2018-09-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=300)),
                ('dropbox_id', models.CharField(max_length=100)),
            ],
        ),
    ]
